<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>GooseTape.Benchmarks</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <!-- BenchmarkDotNet requires public types with public members it can call. -->
    <NoWarn>$(NoWarn);CA1515;CA1822</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="[0.13.0,1.0.0)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GooseTape.NeuralNetwork\GooseTape.NeuralNetwork.csproj" />
  </ItemGroup>

</Project>
